services:
  go-fib:
    build:
      context: ./go-fib
      dockerfile: Dockerfile
    env_file:
      - ./go-fib/.env
    ports:
      - 8081:8080
    restart: unless-stopped
  cs-fib:
    build:
      context: ./cs-fib
      dockerfile: Dockerfile
    env_file:
      - ./cs-fib/.env
    ports:
      - 8082:8080
    restart: unless-stopped
  js-fib:
    build:
      context: ./js-fib
      dockerfile: Dockerfile
    env_file:
      - ./js-fib/.env
    ports:
      - 8083:8080
    restart: unless-stopped
